# Generated by Django 2.0.7 on 2018-07-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=50, null=True)),
                ('maths', models.CharField(max_length=50, null=True)),
                ('science', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='marksheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.User'),
        ),
        migrations.AlterUniqueTogether(
            name='marksheet',
            unique_together={('user', 'grade')},
        ),
    ]
